# Generated by Django 5.1.4 on 2025-01-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_user_email_alter_user_id_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
