# Generated by Django 5.1.4 on 2024-12-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
