# Generated by Django 5.1.4 on 2024-12-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
